### ISSUE TITLE
Weird behavior on some windows.

### ISSUE THREAD

**Issue by domialex** [Ryochan7/antimicro#135]
I use an xbox360 wireless controller to move my mouse.
When I bring up certain windows, for example, the AntiMicro windows, and let's say I want to minimize it with my controller, well after the click the controller doesn't respond and the action doesn't register. The only way to make the controller register again is to use my mouse to minimize the window.

**Comment by Ryochan7** [comment]
It has been a long time but the code has finally been refactored and all external event handling has been moved outside of the main GUI thread. Besides working around this issue, the timers being used to control mouse events is more consistent which allows for better control over the mouse pointer on all platforms.
