### ISSUE TITLE
It is not possible to "while held" select the same set from several sets with the same button

### ISSUE THREAD

**Issue by pieterjanv** [Ryochan7/antimicro#147]
Hi Ryochan7,

I would like to be able to "while held" select the same map by holding the same key in different maps. This is not possible. The same map can only be "while held" selected from different maps by using a unique key in each selecting map.
To simulate this behaviour I have to duplicate the map I wish to "while held" select for each selecting map, the same key selecting a different duplicate map for each selecting map. This feels like a waste of maps.

The reason this happens is that a "while held" selection requires that the corresponding function in the opposite direction is assigned to the same key in the selected map. But I see no need for this. Instead, it seems to me better to be able to independently assign the same key in the selected map, and suppress it during its "while-held" selection to prevent it from firing upon release.

Regards, Pieter Jan

**Comment by Ryochan7** [comment]
Set switching should be tweaked in order to be a bit more flexible when using "While Held" set modifiers.
