### ISSUE TITLE
Alt+Tab not working in Win 8.1

### ISSUE THREAD

**Issue by phob** [Ryochan7/antimicro#156]
Hi,

I've just upgraded to Windows 8.1 and the combination Alt+Tab is not working.
It was perfectly working on Windows 7 thou.
The UAC thing is activated.

**Comment by Emergo** [comment]
Thanks for these comments. I first lost some time trying to get alt tab to work in the pinnacle profiler. until i found these comments. I more or less worked around it using the win hotkeys available in win 8. Pressing "WIN" and "keyb 1" will switch to first position in taskbar; pressing "WIN" and "keyb 2" will switch to second position in taskbar. etc... First create the set of standard commands. e.g. win hk1; win hk2 etc... I is just two event steps: hold and release the win key and press the numerical key . Next these standard commands can be combined  in a joystick command (tested and using now) or probably a cycle command (not tested)

**Comment by Balderick** [comment]
Another alternative to alt + tab is alt +esc (shift + alt + esc) but this only methodicaly cycles focus to each open app.

A more useful solution more akin to alt + tab which shows all open apps in a window which can then be cycled through is to use a copy of the shortcut window switcher.ink  found in C:\Users\Default\AppData\Roaming\Microsoft\Internet Explorer\Quick Launch.

Pasting that to somewhere more convenient like in documents folder or even C:\Users\Default\AppData\Roaming\Microsoft\Windows\Start Menu\Programs" then allows right clicking > properties to set any keybind you wish (not alt + tab though) which then allows easy mapping to controller.
