### ISSUE TITLE
X360 Wireless. LT and RT binds activate when pad powers off

### ISSUE THREAD

**Issue by MaxMeerkat** [Ryochan7/antimicro#164]
Just before Antimicro reports the usual "No Joysticks have been found". Happens all the time with all profiles.

**Comment by Ryochan7** [comment]
With the last few commits that have been made, this problem has pretty much been resolved. The current workaround has less overhead than the old prototype and it should be more maintainable. Thank you MaxMeerkat for bringing up this problem.
