### ISSUE TITLE
msi adds Desktop and Start Menu shortcuts to current user only

### ISSUE THREAD

**Issue by madewokherd** [Ryochan7/antimicro#170]
I'd expect that using a .msi to install to the machine would put the shortcuts in the "public" desktop and start menu so they can be seen by all users. Instead, they go in the current user's desktop and start menu.

**Comment by Ryochan7** [comment]
Thanks for mentioning this. The msi installer should be updated to make shortcuts available for all users.

**Comment by Ryochan7** [comment]
The changes have been made. The msi file for the next release will make the shortcuts accessible to all users on a machine.
