### ISSUE TITLE
Use of 'slots' and 'set selection' together

### ISSUE THREAD

**Issue by Wazkey** [Ryochan7/antimicro#171]
It would be great to use **hold** slot **to change to another set**. Now I think there is no way to do that, since 'set selecting' doesn't work as slots. It seems to me to be very usefull because it prevents from changing set (most important if it is *one way*) having pressed the button by mistake.

**Comment by Ryochan7** [comment]
That feature has been something that had not been feasible within the code before. As it stands now, making set changing work via slots could probably work. They would have to work as one way set selectors. That is the only mode that makes sense for this use case.

**Comment by Ryochan7** [comment]
Okay. A simple prototype works so adding this to the current code base is possible.

**Comment by Ryochan7** [comment]
The current implementation seems to work well enough. At this point, I will close this issue unless there is a reason to open it back up. Thank you for the feature suggestion.
