### ISSUE TITLE
Kinda springy...

### ISSUE THREAD

**Issue by minego** [Ryochan7/antimicro#189]
I've been trying to create a profile that will work with starbound, and it is VERY close to working right... but I have a problem with sticky mouse mode.

In starbound wasd moves the character (left stick, easy) and the mouse controls where the character looks. The character is always in the center of the screen so this works reasonably well with sticky mode. The problem is that putting the cursor in the exact center of the screen causes the character to look to the left, so any time I release the right stick I'm suddenly looking left.

What I'd like here is an option for springy that moves the mouse to the center of the screen when the right stick leaves the deadzone instead of when it enters the deadzone. The effect would be nearly identical but would leave the character looking where I had pointed him when I release the stick.

**Comment by Ryochan7** [comment]
Getting the program to work that way would be pretty simple to code. I had thought about making an offset for placing the cursor slightly away from the center when the stick is moved back to the dead zone.

**Comment by Ryochan7** [comment]
I think that I have come up with something that will work for this use case. A release circle percentage can now be specified. With that set, the mouse cursor will not return to the center of the screen but snap to the appropriate direction around the center point. If the last seen axis values fall below the release circle region, the mouse cursor will stay where it is. Without that, the mouse cursor would move away from the center on release when that is not the desired behavior.

**Comment by minego** [comment]
This sounds like a perfect solution for this case! Thank you.
