### ISSUE TITLE
Ubuntu Vivid repository not working

### ISSUE THREAD

**Issue by Zeioth** [Ryochan7/antimicro#190]
The aplication can be installed manually and work fine, but repositories are not working. Output from running apt-get update:

W:Failed to fetch http://ppa.launchpad.net/ryochan7/antimicro/ubuntu/dists/vivid/main/binary-amd64/Packages  404  Not Found
, W:Failed to fetch http://ppa.launchpad.net/ryochan7/antimicro/ubuntu/dists/vivid/main/binary-i386/Packages  404  Not Found
, E:Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by Ryochan7** [comment]
Thanks for pointing this out. The package is currently building and it will be the last.
