### ISSUE TITLE
Ceasing Development Indefinitely

### ISSUE THREAD

**Issue by Ryochan7** [Ryochan7/antimicro#191]
I figure that I should put some form of notice out there. As of May 04, 2015, I have decided to stop developing antimicro for the foreseeable future. I need to resolve some other problems not related to this project before I can even consider continuing working on any projects. I'm sorry for failing yet again.

**Comment by george-alisson** [comment]
Hey man, don't be so hard on yourself. You did a great work. I'm sure everything will be ok soon and you will be back. Real life should always be priority. Thanks for your awesome work and good luck with your problems!

**Comment by ssokolow** [comment]
I have to agree with @george-alisson. If you feel the urge to work on it, go ahead, but don't feel obligated. It already works beautifully and it's not as if you're being paid for this.

Life happens.

**Comment by pfanne** [comment]
I can only emphasize what @george-alisson and @ssokolow said.
You did some awesome work and having to take a break or stopping forever because of more important issues is in no way a failure.
Your provided many of us with a great open source tool that provided us with finally usable controller support for a lot of games.
Thanks for all you did!

**Comment by Ryochan7** [comment]
Thank you all for the encouragement. After a lot of deliberation, I have decided to resume at least some minor development of antimicro. The major problem has always been with myself and my own criticisms and doubt. I will try my best to improve this program in the future.

**Comment by jsbackus** [comment]
Welcome back!

Look - nothing is perfect, nor is anybody. So, do your best to make a program that scratches any itches you have, enjoy the process, and most importantly, learn to be proud of the end result. Anything beyond that is just icing.
