### ISSUE TITLE
Shift key not registering in advanced window

### ISSUE THREAD

**Issue by Sanocon** [Ryochan7/antimicro#200]
So Because of a game I'm playing, I'm having to use the advanced option for every button since each button has 2 commands. However at least 5 of these commands require a shift [enter letter here] command. However, once i finish programing the advanced commands either shift keys turn into a [NO KEY] once i close the advanced window box. It seems the shift key is being blocked from being used. Is there a way to fix this?

**Comment by Ryochan7** [comment]
Which version of antimicro are you using and which operating system are you running it on? Assigning shift keys in the advanced window works with the most recent code while running the program on Linux.

**Comment by Sanocon** [comment]
Im using windows 8.1 with the non portable windows 64bit of antimicro. Since the game im playing is multiplatform i may use linux.

**Comment by Ryochan7** [comment]
A couple of issues specific to the Windows version have been fixed. Now, Shift can be bound properly in the Advanced window either using the virtual keyboard or from direct keyboard key presses.

**Comment by Sanocon** [comment]
So im guessing i redownload the latest release? Sorry im new to github.....

**Comment by Ryochan7** [comment]
Unless you are a developer, you would normally have to wait for a new stable release to be uploaded to GitHub. With the most recent changes that have been made, it might take some time before I feel that the code is ready for another stable release. However, I have built the most recent code and uploaded a build to my public Dropbox folder.

https://dl.dropboxusercontent.com/u/31073509/antimicro/antimicro-nightly-20150614-win64.zip

There have been some changes in program behavior but I have not itemized those changes in the Changelog file yet. The biggest change is that interpolation is now being done for mouse movement regarding the stick diagonal directions. Another big change is that the mouse acceleration curve has changed to make the low end looser.

**Comment by Sanocon** [comment]
the nightly build works. I'll report any bugs in the future if they pop up.
