### ISSUE TITLE
Cycle reset timer not saving

### ISSUE THREAD

**Issue by ElderCub** [Ryochan7/antimicro#205]
I've been setting up a profile for Witcher 3 for a bit, and I've been having an issue with cycle resets. I'm building a tap:dodge/2tap:roll/hold:sprint button on my A, but no matter what I do, I can't change the reset time on the cycle. Using the UI any changes to the timer will turn off cycle reset, and modifying the XML directly on the <cycleresetinterval>6000</cycleresetinterval> will not change it from 6 seconds.

**Comment by Ryochan7** [comment]
Thank you for mentioning this problem. The issue has now been fixed.

**Comment by ElderCub** [comment]
I'm new to github, when will the fix be live?

**Comment by Ryochan7** [comment]
Unless you want to compile the code yourself, I would have to make a new package and upload it. Which package are you using?

**Comment by ElderCub** [comment]
Currently, I'm using 2.16 x32 bit portable version.

**Comment by Ryochan7** [comment]
I'm sorry that I had not gotten back to you. There were some issues with the last release that I have been working on correcting. At this point, I think I have fixed those problems and improved things in the process. There should be a major release published soon.

**Comment by Ryochan7** [comment]
Version 2.17 is now up. https://github.com/Ryochan7/antimicro/releases/download/2.17/antimicro-2.17-portable-win32.zip
