### ISSUE TITLE
Wiimote Support

### ISSUE THREAD

**Issue by Papermanzero** [Ryochan7/antimicro#208]
Currently I am using GlovePie for several games to use either the 360 or Wii controller.
However GlovePie is neither open source nor maintainend and I am searching an alternative, which contains the same functionality like GlovePie.
I found this project and I am pretty amazed about the possibilities of antimicro.
However it lacks support for the wiimote and it's attachments (nunchuck, classic controller and motion plus).
It would be great to implement mapping possibilities for the wiimote and its accessories.

Especially for strategy, shooter, adventure, J'n'R games it would be great to map the keyboard/mouse to the wiimote and its attachments (e.g. classic controller for J'n'R and Nunchuck for shooters).

**Comment by Papermanzero** [comment]
http://public.vrac.iastate.edu/vancegroup/docs/wiiuse/

**Comment by Ryochan7** [comment]
Using a Wiimote for interfacing with a PC has been something that has interested me for a little while. I am not sure if I would want to enter into that space myself though. I have checked out some implementations and some projects have gotten pretty close to a solution. At this point, [Touchmote](http://touchmote.net/) seems like the project that is the furthest along to having a real solution for using a Wiimote on the PC but it isn't really usable for playing PC games using a Wiimote + Nunchuck as of yet. An fpsmouse mode was recently introduced so maybe the project will be able to hammer out a complete solution in the future.

Anyway, thank you for pointing out the Wiimote library.

**Comment by Papermanzero** [comment]
I fully agree.
Touchmote is more or less a solution to navigate through Windows 8 in a comfortable way from the couch without a big hassle concerning the setup. 
With Antimicro you have to think about how to adjust the different settings like mouse acceleration. WiiUse is a good library in combination with SDL. Especially the extension like Nun-Chuck, Motion Plus and Classic Controller are already implemented.  At least the buttons can be already mapped.

I am still using GlovePie, because it is the only solution to provide all kind of fine-tuning possibilities. Although GlovePie needs basic knowledge how to script, you can adjust almost everything.

**Comment by Ryochan7** [comment]
I think that experimenting with other projects that are much further along regarding Wiimote support will be the better route to take. Just reading the IR sensor bar and interpreting proper screen coordinates seems to be enough of a challenge without having to also figure out a curve that makes sense for how the Wiimote behaves. I will continue to keep track of Touchmote and see how that project progresses.

Hopefully someone will come up with a solution that could also eventually be used for a Linux program. Having a Metroid Prime 3 like experience on SteamOS would be pretty cool.

**Comment by Papermanzero** [comment]
You are right. Meanwhile there is a better approach which would be perfectly compliant to Anti-Micro.

**Comment by Ryochan7** [comment]
Playing around with GlovePIE and Touchmote has been interesting. It is also nice to finally have a copy of Metroid Prime 3 again so I have a reference for how this kind of control scheme worked in the few Wii games that utilized it. One thing that I wish I could test would be Motion Plus support. Even with the 0.46 beta version of GlovePIE, it can't read any gyro data but everything else works. Using gyro data from Motion Plus might be more useful than using IR but I have no way to test it unless I want to find and purchase a different Wiimote or the Motion Plus accessory for my older Wiimote.
