### ISSUE TITLE
how you apply different profiles to different controllers? CLI

### ISSUE THREAD

**Issue by gotbletu** [Ryochan7/antimicro#212]
- Using 64bit linux machine.
- Works fine, if i manually select in the GUI profiles for player 1 on controller 1 and profile 2 on controller 2.
- **Does not** work when using the command line to do this for me.

Works fine for 1 player

    antimicro -d --profile-controller 1 --profile ~/player_1_xbox360.joystick.amgp

**Does not** work when trying 2 player:

    antimicro -d --profile-controller 1 --profile ~/player_1_xbox360.joystick.amgp --profile-controller 2 --profile ~/player_2_xbox360.joystick.amgp

Is it not possible to do 2 profile flags on one line? Or is there a workaround or something i am missing?

**Comment by Ryochan7** [comment]
Currently there is no way to switch different profiles for multiple controllers in one call. This issue has been raised before but I have never gotten around to putting something together.

**Comment by gotbletu** [comment]
I see, hopefully we have that one day =)

In the meantime, this is the **workaround** I am using, Hope it helps anyone

    # change the settings to read only, sometimes it conflicts with loading profiles from commandline
    rm ~/.config/antimicro/antimicro_settings.ini
    touch ~/.config/antimicro/antimicro_settings.ini
    chmod -w ~/.config/antimicro/antimicro_settings.ini


    # start multiple antimicro instance
    # example: loading 2 profiles and running a wine/playonlinux game
    killall antimicro ; antimicro -d --tray --profile-controller 1 --profile ~/.config/antimicro/mugen_player_1_xbox360.joystick.amgp && antimicro -d --tray --profile-controller 2 --profile ~/.config/antimicro/mugen_player_2_xbox360.joystick.amgp ; playonlinux --run "Street Fighter IV" && killall antimicro

**Comment by Ryochan7** [comment]
I think the current `--next` argument should be enough to allow multiple profiles to be specified in one call now.

**Comment by gotbletu** [comment]
Which version has the --next flag? dont see that in the manpages

**Comment by Ryochan7** [comment]
It is available in 2.19.2. The documentation didn't get added to the manpage this time around but it is available if you run antimicro with --help.
