### ISSUE TITLE
libgcc_s_seh-1.dll missing

### ISSUE THREAD

**Issue by Stabington** [Ryochan7/antimicro#213]
Can't run the 64-bit Windows binaries. Missing that .dll
2.18 that is

**Comment by Ryochan7** [comment]
The 64 bit builds should be using siji. I had thought about migrating to use the seh version when I found issues with the main mouse timer under the siji build. I thought I double checked the version being used but apparently a test CMake command string must have been used while building the application. I'll get that fixed.

**Comment by WAZAAAAA0** [comment]
Same problem here, Windows 7 Ultimate 64-bit SP1, was about to write this issue.

**Comment by Ryochan7** [comment]
I should have checked the build kit in Qt Creator as well. The new builds have been tested and are now up.
