### ISSUE TITLE
Some button presses not detected on Razor Sabertooth.

### ISSUE THREAD

**Issue by Masklein** [Ryochan7/antimicro#221]
The guide, left stick and right stick buttons are not detected by antimicro.  When I go to map buttons the button mapping does not detect them either.

**Comment by Ryochan7** [comment]
Is there some way that an axis is active? The mapping dialog window will not interpret any other input if an axis or a button is already active.

**Comment by Masklein** [comment]
The 'Last Axis Event' field in the mapping window does not report any axis events when I push in the L and R buttons.  It does detect when the joysticks are moved along their axis.

So no it does not seem that any other inputs are being read while pressing the stick buttons.

**Comment by Ryochan7** [comment]
Have you tried the controller in other programs that use evdev? I would recommend that you try out evtest and sdl2-jstest and see how your controller behaves in those two programs.

**Comment by Masklein** [comment]
I will give those applications a try when I get home tonight.

If it helps, I've used Xpadder in the past and had no issues.

**Comment by Masklein** [comment]
I am not finding any easy to use executable for either application you
suggested and I am not so inclined to go through a bunch of hoops to get
them working.  If you know a link that has a something then pass it along,
otherwise I will not be pursuing this further.

**Comment by Ryochan7** [comment]
When you mentioned that you were having problems, I initially assumed that you were running some Linux distro as I figure SDL would handle the Razor Sabertooth as an XInput device on Windows. There are a couple of programs that might be useful for testing in this case. The first would be to try the controller in Steam Big Picture Mode and see the controller is completely mapped there. Another option is a program similar to the Game Controller Mapping dialog in antimicro. It is an SDL2 Gamepad Tool that works in Windows and it can be found at http://www.generalarcade.com/gamepadtool/.

**Comment by Masklein** [comment]
Steam Big Picture worked overall with the controller.  I couldn't find a
specific instance where I could use the thumb stick buttons.

SDL2 Gamepad Tool was able to detect my pressing of every button on the
game pad.  Screen shot attached.

**Comment by Ryochan7** [comment]
I am not sure what is going on then. One crazy thing that you could try is to copy the SDL2.dll file bundled with SDL2 Gamepad Tool and copy it to the antimicro folder. Both programs use SDL 2.0.3 but the file size of the dll files are different. Maybe the version bundled with SDL2 Gamepad Tool is compiled a bit differently than the stock binary library. Also, it is interesting to see that Steam uses SDL 2.0.4 which doesn't have a public release yet.

**Comment by Masklein** [comment]
I had some time to try this out.

Replacing the SDL2.dll gives the error shown in the attached screen shot.

[image: Inline image 1]

I tried remapping the Stick button to one of the extra keys does not
register the newly mapped key either.  Remapping keys that antimicro does
detect will still detect the key press on the newly mapped key.

**Comment by Masklein** [comment]
I reset the controller mappings by disabling the only mapping I had from
Options > Settings > Controller Mappings.  I then selected Options > Update
Joy Sticks.  This wiped out the profile (expected), but it also exposed
buttons that would now highlight when the L and R stick buttons are pressed.

So maybe the profile is messed up in some way?  I've attached the profile
if you are curious.

**Comment by Ryochan7** [comment]
Thank you for continuing to look into this. It looks like there will be problems in case a mapping doesn't contain all expected buttons. I should look into making the mapping dialog window a bit more flexible.

**Comment by Ryochan7** [comment]
The mapping dialog window has been changed to ensure that raw input is being used at all times. Hopefully this problem will not exist anymore.

**Comment by Masklein** [comment]
I will try the latest build when I get home and see if this helps.
