### ISSUE TITLE
Unusual high CPU usage issue persists in V 2.19

### ISSUE THREAD

**Issue by Thrasher1984** [Ryochan7/antimicro#223]
As I see I'm a little late as the original topic was closed but I just wanted to let the developer know that the high CPU load issue still persists.

On a clean install of the current 64 bit version 2.19 one of the cores of my Phenom II X4 processor is constantly under full load when no game controller device is plugged in. I'm running Windows 7 Ultimate SP1.

**Comment by Ryochan7** [comment]
I have checked and confirmed that this bug has popped up again. Fix one problem and two more show up has been a common trend for this project lately.

**Comment by Ryochan7** [comment]
I fixed another problem where routines for initially setting up the main mouse timer would only run if a controller was connected. Without those routines being called, the mouse timer would have a interval of 0 ms which would result in 100% load on one CPU core. A new patch release will have to come out soon.

**Comment by Thrasher1984** [comment]
Your hard work on this software is much appreciated! I'd prefer antimicro any day over JoyToKey or Logitech Gaming Software 5.10.

**Comment by Ryochan7** [comment]
Version 2.19.1 is now out and it resolves this problem.
