### ISSUE TITLE
compilable headless version (without Qt dependencies)

### ISSUE THREAD

**Issue by MelTraX** [Ryochan7/antimicro#225]
Hey there,

first of all thanks for this amazing project.

Do you use Qt only for the GUI or also for handling key inputs? If all the event handling needs Qt, just close this request.

But if Qt is only needed for the GUI (so for defining profiles), it would be cool if antimicro could be compiled headless.

My usecase:

I have a bootable USB stick based on the Lubuntu Live ISO that contains ~80 games and antimicro is used to provide gamepad support for quite a few of those. Being a live CD, any packages I have to install, are kept in RAM and depending on the machine, 40 MiB for Qt is quite a bit (and the profiles would be done beforehand anyway).

It's not terribly important but if it's not much work, it would be highly appreciated. If you just give me a hint or two, I might also be able to do it myself. But like I said, not if the core event handling needs Qt.

**Comment by Ryochan7** [comment]
Qt libraries are used for more than just creating the GUI. The Qt event system and many data types defined in Qt are used throughout the classes that make up antimicro. It would be theoretically possible to remove the use of QtWidgets provided that a command line bootstrap was made. I am not sure how much space that would really save though.

**Comment by MelTraX** [comment]
Nevermind then. Thanks for the reply and of course this awesome piece of software. :)
