### ISSUE TITLE
Window starts at (0, 0) / potentially behind the task bar

### ISSUE THREAD

**Issue by Gama11** [Ryochan7/antimicro#226]
The window always seems to be positioned at (0, 0). Since I have my taskbar on the left, that means the window is partially behind it.

![](http://i.imgur.com/aRx644w.png)

In general, the most sensible option for applications that don't remember the last position is probably to  be positioned in the screen center.

**Comment by Ryochan7** [comment]
antimicro should remember its last known window position and window size. Those settings should be restored after opening the application again. I have never really noticed a problem with that on Windows and the code that handles those settings is still intact. I will have to test it and make sure that the settings are being honored.

**Comment by Ryochan7** [comment]
I tested it and I don't experience this kind of problem with version 2.19.1. The window position and window size are restored as intended.

**Comment by Gama11** [comment]
Hm, interesting...

This might actually be related to other issues I've been having. It seems that as soon as antimicro accesses the file system in any way, it crashes -
* load a config file - crash
* save a config file - crash
* change anything in Options -> Settings and close antimicro - crash (I presume it attempts to write the changes to the file system)

I was on version 2.18.2 when I reported this btw, but updating to latest (2.19.1) didn't make any difference. Both of these are portable versions.

**Comment by Gama11** [comment]
I also just got the `.msi` version of 2.19.1 - same issues there.

**Comment by Ryochan7** [comment]
I am not sure what could be going wrong. It seems like any I/O operation fails in your case. The operations being used to load profiles and read/save settings should fail gracefully; I am not sure if profile saving would fail gracefully though. I have attempted to force a failed profile read and a failed saving of application settings on my Sabayon laptop. Both failed without any major problems. I will have to give this a shot on Windows and see if the behavior is different.

**Comment by Ryochan7** [comment]
I still haven't been able to reproduce this problem. Every failed read and write operation fails gracefully for the most part; a failed saving of a profile isn't obvious in the program but no errors occur in the program.

**Comment by Ryochan7** [comment]
There has been some more mutex locking added in some places. Hopefully that will take care of some of the problems that you have been experiencing. Unfortunately, it is a shot in the dark as I have never encountered problems with that code but the possibility for problems existed. I am trying to get version 2.19.2 out today so you should have a new version to test soon.

**Comment by Gama11** [comment]
Seems like that actually fixed the issue - good job, considering you didn't have much to go on without a way to reproduce the problem! :)

It would still be neat if the window initially started in the screen center instead of (0, 0), but that's pretty minor I guess.
