### ISSUE TITLE
conditional set change

### ISSUE THREAD

**Issue by AssFat** [Ryochan7/antimicro#231]
i been wondering if its possible to have the set change conditional. for example have it change after a release command or a string of commands. like set change have its own slot.. would open up many many doors.

**Comment by Ryochan7** [comment]
Set changing can be assigned to a slot. That allows for a little bit more flexibility than using the normal set changing procedure.

**Comment by AssFat** [comment]
awe damn. i just looked and i see the option now. maybe my old version didnt have it or my eyesight is improving

**Comment by Ryochan7** [comment]
Looking back at previous releases, it looks like this has been an option since version 2.11. It is a more obscure feature so it is a bit easy to miss.
