### ISSUE TITLE
stick sensitivity/dead zone

### ISSUE THREAD

**Issue by AssFat** [Ryochan7/antimicro#234]
maybe im not seeing the way to do this. but im having sensitivity issues with an xbox pad.
i have the dead zone set at  28,000(thats almost max) and the max zone maxed out. still, at center im getting movement. seems as thought the dead zone isnt working properly or maybe windows is sending info also?...

**Comment by Ryochan7** [comment]
If the stick is being used to alter settings, the dead zone setting should take effect on the next stick move. Having stick events still get generated afterwards while the stick is in the dead zone should not happen.

**Comment by AssFat** [comment]
not triggering commands. just the curser or scrolling kinda wonders. may not me a thing this app can help
