### ISSUE TITLE
Compile error against Qt5: Missing Qt5Widgets

### ISSUE THREAD

**Issue by rogerxxxx** [Ryochan7/antimicro#236]
Compiling with Qt5 support
CMake Error at CMakeLists.txt:496 (find_package):
  By not providing "FindQt5Widgets.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "Qt5Widgets", but CMake did not find one.

  Could not find a package configuration file provided by "Qt5Widgets" with
  any of the following names:

    Qt5WidgetsConfig.cmake
    qt5widgets-config.cmake

  Add the installation prefix of "Qt5Widgets" to CMAKE_PREFIX_PATH or set
  "Qt5Widgets_DIR" to a directory containing one of the above files.  If
  "Qt5Widgets" provides a separate development package or SDK, be sure it has
  been installed.

**Comment by rogerxxxx** [comment]
I get the above error on my Gentoo Linux platform,  with =games-util/antimicro-2.10.1 =games-util/antimicro-2.19.2 versions, except when using "QT_SELECT=4 emerge antimicro".

I'm not sure if I'm missing a build depend or configure flag for one of the Qt packages, or other syntax error.  If anybody knows anything, please let me know so I can further escalate this bug elsewhere if needed, or if I just need to fix the package compiling options, etc.

**Comment by Ryochan7** [comment]
I am using Sabayon but I think this should apply to base Gentoo as well. The Qt5WidgetsConfig.cmake belongs to the package dev-qt/qtgui. You need to have that package installed on your system in order to build antimicro from source with Qt5 support.

**Comment by rogerxxxx** [comment]
$ qlist =dev-qt/qtgui-5.4.2-r1 |grep *widget* -i
1 :-(

$ qlist =dev-qt/qtgui-4.8.6-r4 |grep *Widget* -i
1  :-(

Not finding Qt5WidgetsConfig.cmake, or anything similar within the installed files.  Possible a configure flag needs to be specified?

dev-qt/qtgui-4.8.6-r4 (accessibility cups exceptions glib mng qt3support tiff xv -aqua -debug -egl -gtkstyle -nas -nis -pch -trace -xinerama)

dev-qt/qtgui-5.4.2-r1 (dbus gif harfbuzz jpeg png udev xcb -accessibility -debug -egl -eglfs -evdev -gles2 -gtkstyle -ibus -test)

And just struck me, you're on Sabayon, so I should be seeing something!

Most I get is the following, omitting debug files and irrelevant user files.
$ locate *idgets* |grep qt5 -i
/usr/include/qt4/Qt/q3widgetstack.h
/usr/include/qt4/Qt3Support/q3widgetstack.h
/usr/lib64/qt4/plugins/accessible/libqtaccessiblewidgets.so

Those *.cmake files sounds like they're part of the original source package files, and are usually not installed except for headers files. (ie. *.h)

$ fgrep /usr/include/qt4 -r -e Qt5Widgets -i
1 :-(

$ fgrep /usr/include/qt5 -r -e Qt5Widgets -i
1 :-(

Still not finding anything relevant.  This isn't a critical issue, as there's a workaround, for now.  If you can give me a better function name or other info in your spare time, I can further search to pin down this issue.

**Comment by Ryochan7** [comment]
I was thinking about the Qt5GuiConfig.cmake file instead of Qt5WidgetsConfig.cmake. It looks like the dev-qt/qtwidgets package is what you should look for instead. On my Sabayon system, the relevant cmake files can be found at:

    /usr/lib64/cmake/Qt5Widgets/Qt5WidgetsConfig.cmake
    /usr/lib64/cmake/Qt5Widgets/Qt5WidgetsConfigVersion.cmake

**Comment by rogerxxxx** [comment]
Found it.  Looks to be a packaging error.

# emerge dev-qt/qtwidgets

The fore mentioned package install solves building antimicro against Qt5.  Not required for building against Qt4.
