### ISSUE TITLE
Feature:  Add Debian Packaging

### ISSUE THREAD

**Issue by EmperorArthur** [Ryochan7/antimicro#237]
I'm planning on adding Debian packaging support.  Basically the "debian" folder and some of the associated files.

Adding at least the "Build-Depends" means that every debian user should know exactly what packages are required to build it.  It also allows for some regression testing using sbuild.

Want an opinion before I go overboard with this.

**Comment by Ryochan7** [comment]
I already have some base Debian packaging files created for use when building the Wheezy and Jessie deb files. It should well enough as a base for the version that you would like to make.

https://github.com/Ryochan7/antimicro-packaging/tree/master/debian-versions
