### ISSUE TITLE
Antimicro 2.19.3 renders single-core WinXP unusable if no joystick is plugged in

### ISSUE THREAD

**Issue by ssokolow** [Ryochan7/antimicro#246]
I just downloaded the latest noSSE-win32 release for my WinXP nostalgia machine (an Athlon64 3200+, which is a single-core processor) and, because I forgot to plug the joystick in *before* starting antimicro, it pegged the CPU usage at 100% so hard that the system was taking upwards of two minutes for it to react to even the most basic of input like button hover glows.

I've had this problem on my dual-core Linux box but I never realized it was so bad that, on a single-core WinXP machine, it could starve the rest of the system for CPU cycles.

**Comment by Ryochan7** [comment]
I am trying it now on my Sabayon box and I don't see a big spike in CPU load when no joystick is plugged in at application launch. There shouldn't be anything that would only make the CPU load spike on any version of Windows but I will have to test this out on Windows just to be sure.

**Comment by Ryochan7** [comment]
Although I didn't experience it myself while testing the noSSE version on Windows, I have added an extra precaution in the most recent commit that should help.

**Comment by ssokolow** [comment]
Thanks. I'll let you know how it works out when an updated build is available.

**Comment by Ryochan7** [comment]
The latest Windows packages are now up.

**Comment by ssokolow** [comment]
Yep. That seems to have solved it.
