### ISSUE TITLE
Starting programs with arguments

### ISSUE THREAD

**Issue by ErickPetru** [Ryochan7/antimicro#248]
It's really nice that we can bind a button sequence to launch a program. But it would be really more powerful if we could append arguments after the path, i.e. put a *steam://open/bigpicture* argument after my *Steam.exe* path could launch Steam already in Big Picture Mode, if it isn't running.

**Comment by Ryochan7** [comment]
On the Windows side, I would usually use batch scripts for situations like that. antimicro would then be set to launch the batch script. On Linux, bash scripts would be used, maybe in combination with Lutris, for launching programs with special arguments. I had thought about adding an arguments option but I didn't feel like it was necessary at the time. It wouldn't take much to add that functionality.
