### ISSUE TITLE
Can't assign "CTRL HOME" to a button.

### ISSUE THREAD

**Issue by Kaganis** [Ryochan7/antimicro#249]
Using the latest version of antimicro on Vista.

I can't set the keyboard combination CTRL + HOME to a joystick button.  As soon as you leave the "Advanced" setting page, it reverts to just HOME.

I'm pretty sure I'm doing it right, since I can set up CTRL + END without any problems.

**Comment by Ryochan7** [comment]
If you use the virtual keyboard in the regular button edit window, you can add both slots fine. Just assigning it directly in the Advanced window doesn't work though. I will take a look into this.

**Comment by Ryochan7** [comment]
I have found the reason behind the problem. When the Home key is pressed, Qt selects the first item in the list before antimicro has a chance to read the key code and make a new slot. The Home key will have to be added to an exceptions list so that does not happen. The End key should also be added.
