### ISSUE TITLE
3DS Wireless Support

### ISSUE THREAD

**Issue by lordsolrac** [Ryochan7/antimicro#251]
As you read. I found no success on configuring the Nintendo 3DS as a controller. I know it sounds silly and stupid, but I wouldn't make this issue if it weren't because the 3DS *Can* be used as a controller on the PC.
[Reference Post, 3DSController a Homebrew for 3DS](https://gbatemp.net/threads/3ds-controller.375443/)

Most probably because I haven't found support for controllers over Wi-Fi.

Think it could be implemented? Or am I just seeing an option around here? (Any alternatives though?)

**Comment by Ryochan7** [comment]
As long as the driver package being used allows Windows to see the 3DS as a DirectInput or XInput compatible gamepad then antimicro should be able to detect the 3DS. There should be nothing in antimicro to prevent the device from working.

**Comment by lordsolrac** [comment]
There is no  driver. The Windows application checks for an IP Adress of a 3DS Running the application and then goes for the port (8889). They use vJoy though.

**Comment by lordsolrac** [comment]
Bump?

**Comment by Ryochan7** [comment]
Since the software is using vJoy then any virtual controllers should be detected just fine. I have only played with vJoy a little bit but antimicro can detect a virtual controller created by that program as a DirectInput compatible gamepad. Hopefully you will be able to work out the problem with that setup. Unfortunately, I don't think that there is much more that I can do to try to help out.

**Comment by lordsolrac** [comment]
So it should work, but does Antimicro detect controllers over wifi then?

**Comment by ssokolow** [comment]
@lordsolrac: I believe what Ryochan7 is saying is that vJoy will handle presenting the WiFi attachment as a normal-looking Joystick and then Antimicro will map that normal looking joystick to fake keyboard/mouse input.

**Comment by Ryochan7** [comment]
That is pretty much what I was saying. The server software running on your Windows system should be responsible for reading the report generated by the client software running on the 3DS and then converting it to actions on the vJoy virtual controller. That way Windows will be able to see the activity and then other programs will then be able to read the generated events. If no virtual controller is seen under the Game Controller settings in the Windows Control Panel then no other program will see the 3DS as a controller.
