### ISSUE TITLE
Set changing with triggers broken since 2.20

### ISSUE THREAD

**Issue by matfas** [Ryochan7/antimicro#254]
Somewhere between 2.19.3 and 2.20 set changing events assigned to triggers broke for me. I am currently using Manjaro 15.09.

The last commit with this feature working is: 66398f56e0cadd2b646790d811ccb37a3010b878
The commit after that one gives me a segmentation fault when I change sets: ef8061d20c7c457ea9d36ab28ce25bba2dbfec99
With the commit after that one (and probably all of the following commits) set changing events assigned to triggers seem not to be working anymore: f90583691c64c63a27990d2d14e580bc28d9f9e5

**Comment by Ryochan7** [comment]
That report makes it sound like an invalid pointer problem. I will look into it.

**Comment by TuRDMaN** [comment]
I was running version 2.20.2 x64 portable on Windows. The first version I have ever tried. I was tearing my hair out trying to figure out why sets were not changing when I was pulling the triggers. There were no errors or anything, it just simply did not switch sets.

I have now downloaded version 2.19.3 and everything works as expected.

**Comment by Ryochan7** [comment]
Some old test code was affecting set switching for axes. This problem has been fixed with the most recent commit.

**Comment by matfas** [comment]
Thanks a lot for fixing this problem. Current builds were basically not usable for me because of this bug. Now I can update antimicro again. :)
