### ISSUE TITLE
Configure failure with cmake 3.4

### ISSUE THREAD

**Issue by Earnestly** [Ryochan7/antimicro#255]
* gcc 5.2.0
* cmake 3.4.0
* linux 4.3.0

```
% cd antimicro
% cmake -DCMAKE_INSTALL_PREFIX=/usr -DUSE_SDL_2=ON
```

```
-- The C compiler identification is GNU 5.2.0
-- The CXX compiler identification is GNU 5.2.0
CMake Error at /usr/share/cmake-3.4/Modules/Compiler/GNU-C.cmake:28 (message):
  CMAKE_C_STANDARD_COMPUTED_DEFAULT should be set for GNU (/usr/bin/cc)
  version 5.2.0
Call Stack (most recent call first):
  /usr/share/cmake-3.4/Modules/CMakeCInformation.cmake:33 (include)
  CMakeLists.txt:21 (project)


-- Configuring incomplete, errors occurred!
See also "/home/earnest/build/pkgbuilds/antimicro-git/src/antimicro/CMakeFiles/CMakeOutput.log".
```

If there is any more information that I can provide, please ask

**Comment by Ryochan7** [comment]
This doesn't seem like a problem that I would be able to fix. It looks like that error occurs before executing anything specific in the project's CMakeLists.txt file. I am using CMake 3.3.1 on my Sabayon box and it works with that version.

**Comment by Earnestly** [comment]
@Ryochan7 Sorry for not getting back to you, this was a bug in cmake 3.4.0 when building with `-flto`. https://bugs.archlinux.org/task/47113 and fixed in https://cmake.org/gitweb?p=cmake.git;a=commitdiff;h=716a09b9

I'll close this as it turned out all cmake stuff was broken and not just antimicro.  I was too hasty, sorry about that.
