### ISSUE TITLE
Assign keyboard slots to activate in sequence

### ISSUE THREAD

**Issue by apathy27** [Ryochan7/antimicro#256]
is it possible to assign a combination of keyboard slots to activate in a sequence starting from like F then G then H like performing moves like fireball (quarter circle forward + punch) in fighting games like Street Fighter in just one button push?

**Comment by Ryochan7** [comment]
For that type of sequence, you would probably want to add some Pause slots in between the keys that you want to have pressed. An example sequence would be like the following.

    F -> Pause 0.01 -> G -> Pause 0.01 -> H

**Comment by apathy27** [comment]
i have tried this but sometimes it skips the first key and starts from the second one and sometimes it activates all keys well. And will it release the keys before the Pause slots?

**Comment by apathy27** [comment]
i have tried this but sometimes it skips the first key and starts from the
second  or any other keys in the middle...

**Comment by Ryochan7** [comment]
The normal routine is that the key will be held for a period of time before releasing it and activating the Pause slot. The amount of time that keys would be pressed can be changed by editing the **Key Press Time** either for the whole profile or by assigning **Press Time** slots in the sequence; the default time is 100 ms.

I will look into the issue that you mentioned about keys not getting activated in a sequence.

**Comment by apathy27** [comment]
yeah because certain keys are getting skipped in the middle or at the start
most of the time and very few times they get activated in a sequence

**Comment by Ryochan7** [comment]
I have finally tried this with version 2.20.2 and the previously written sequence is working as expected for me. The keys get activated in the expected order (tested in text editor and xev program) and a currently executing sequence can be reset as expected.

**Comment by apathy27** [comment]
cool!...so whats the procedure?

**Comment by Papermanzero** [comment]
Can be found here: https://github.com/Ryochan7/antimicro/wiki/Advanced-Slot-Explanation

**Comment by apathy27** [comment]
well i figured it out too...what u do is first put a pause slot (o seconds
is enough). then add slots of which ever keys you want to get activated
with Press Time slot (of minimum 0m0.02 seconds)  before each key slot. if
its 2 or more keys you want to be pressed together included in the sequence
then Press Time then the 2 or multiple key slots. different games require
different timing so the press time may have to be more depending on the game
