### ISSUE TITLE
Binding mouse movement in the Advanced>Assignments window

### ISSUE THREAD

**Issue by anijatsu** [Ryochan7/antimicro#258]
Being on Windows 10, I can't figure out a way to make a macro in advanced assignments that would first move my mouse left, then up, so the cursor could reach a button in a particular's game UI.
The only way that I found out to add mouse movement to the chain, is by first mapping it as a single key/button, then editing the chain. That however doesn't allow to add the second movement which is necessary in my case.
Am I missing something?

**Comment by Ryochan7** [comment]
The regular button edit window can be used along with the advanced window. You would highlight the slot in the advanced window that you want to assign and then press the appropriate button in the regular button edit window. That way, you can add mouse movement into other slots in a sequence.
