### ISSUE TITLE
Trying to switch sets when the L trigger is held down

### ISSUE THREAD

**Issue by fitret** [Ryochan7/antimicro#259]
I am trying to set it so that holding down the L trigger switches sets, and I can't get it to work.

So far what I've determined is that antimicro is picking up the L trigger only when it goes back into the deadzone. If i hold the button down, I am unable to get any button actions to occur - I have to release the trigger before it will actually doing any of the switches. I've tried both using the Assignments as well as the actual Set Selector (including the "while held") option and none seem to work, and I've been playing with the Deadzone + max values while watching it.

It appears that the trigger occurs (i.e. I can see it highlight in blue, and if I switch it to a physical button, like the 1 key, that fires), but the set selection doesn't take place until it releases. I've tried implementing it multiple different ways, but no matter what I do I can't get something to happen while the trigger is between the deadzone and the max (or beyond the max) - it has to return from that first, which doesn't accomplish what I am looking for.

Can't figure out if I'm doing this wrong if there's a problem with Xbox One controllers on 64-bit Windows 10 (at least, that's my config).

Here's my full config file: http://pastebin.com/zBmePtTG

And the relevant sections for my current implementation. I've tested this with buttons and it works fine, but I can't get the triggers to work. Changing back to set 1 works just fine, but changing to set 2 requires that the trigger be released, which fails the purpose of this script, which is to switch sets when the button is held. Using the predefined "Switch to set 2 when button is held" *also* does not work.

```xml
<set index="1">
            <trigger index="1">
                <deadZone>25487</deadZone>
                <maxZone>32737</maxZone>
                <throttle>positive</throttle>
                <triggerbutton index="2">
                    <slots>
                        <slot>
                            <code>1</code>
                            <mode>setchange</mode>
                        </slot>
                    </slots>
                </triggerbutton>
            </trigger>
            <trigger index="2">
                <deadZone>6000</deadZone>
                <triggerbutton index="2">
                    <slots>
                        <slot>
                            <code>1</code>
                            <mode>mousebutton</mode>
                        </slot>
                    </slots>
                </triggerbutton>
            </trigger>
</set>
<set index="2">
            <trigger index="1">
                <deadZone>0</deadZone>
                <maxZone>32737</maxZone>
                <triggerbutton index="2">
                    <slots>
                        <slot>
                            <code>10</code>
                            <mode>release</mode>
                        </slot>
                        <slot>
                            <code>0</code>
                            <mode>setchange</mode>
                        </slot>
                    </slots>
                </triggerbutton>
            </trigger>
            <trigger index="2">
                <deadZone>6000</deadZone>
                <triggerbutton index="2">
                    <slots>
                        <slot>
                            <code>3</code>
                            <mode>mousebutton</mode>
                        </slot>
                    </slots>
                </triggerbutton>
            </trigger>
</set>
```

**Comment by fitret** [comment]
Here's my full config file: http://pastebin.com/zBmePtTG

And the relevant sections for my current implementation. I've tested this with buttons and it works fine, but I can't get the triggers to work. Changing back to set 1 works just fine, but changing to set 2 requires that the trigger be released, which fails the purpose of this script, which is to switch sets when the button is held. Using the predefined "Switch to set 2 when button is held" *also* does not work.

<set index="1">
            <trigger index="1">
                <deadZone>25487</deadZone>
                <maxZone>32737</maxZone>
                <throttle>positive</throttle>
                <triggerbutton index="2">
                    <slots>
                        <slot>
                            <code>1</code>
                            <mode>setchange</mode>
                        </slot>
                    </slots>
                </triggerbutton>
            </trigger>
            <trigger index="2">
                <deadZone>6000</deadZone>
                <triggerbutton index="2">
                    <slots>
                        <slot>
                            <code>1</code>
                            <mode>mousebutton</mode>
                        </slot>
                    </slots>
                </triggerbutton>
            </trigger>
</set>
<set index="2">
            <trigger index="1">
                <deadZone>0</deadZone>
                <maxZone>32737</maxZone>
                <triggerbutton index="2">
                    <slots>
                        <slot>
                            <code>10</code>
                            <mode>release</mode>
                        </slot>
                        <slot>
                            <code>0</code>
                            <mode>setchange</mode>
                        </slot>
                    </slots>
                </triggerbutton>
            </trigger>
            <trigger index="2">
                <deadZone>6000</deadZone>
                <triggerbutton index="2">
                    <slots>
                        <slot>
                            <code>3</code>
                            <mode>mousebutton</mode>
                        </slot>
                    </slots>
                </triggerbutton>
            </trigger>
</set>

**Comment by Ryochan7** [comment]
There probably isn't anything wrong with your config. This problem is related to issue #254 which was regarding set switching being broken for triggers. The fix ended up being minor but I had not touched this project in a while. I don't know when I will get around to making a new version which includes the fix.
