### ISSUE TITLE
Is there a way to disable or remove the "wizard"

### ISSUE THREAD

**Issue by Earnestly** [Ryochan7/antimicro#261]
So apparently, when moving configurations, I started antimicro and was greeted with a very unwelcome "wizard" system that forces me to click through a bunch of "next" buttons.  Is there a way to disable or remove this "feature" at compile-time or a command-line flag (which would sadly require yet-another-wrapper, sigh) to prevent it from happening?

If not, would you be willing to either take this issue as a feature request for its removal?

**Comment by Earnestly** [comment]
Oh my goodness, there are tanslation files everywhere for this, of course in XML; it's going to take an effort to get rid of all this...

**Comment by Ryochan7** [comment]
I was thinking about this recently and the next version should probably have something like a `--skip-wizard` flag. As for removing it entirely, I am not so sure about that. Maybe a compile time flag along with the command line flag would be fine.

**Comment by Earnestly** [comment]
I think removing it entirely is the right course of action, wizards have never been good design, something we don't need to inherit from decades of failiure from Windows.  I'm currently writing up a patch to remove it all.
