### ISSUE TITLE
Problems with non-ASCII characters in user profile folder name

### ISSUE THREAD

**Issue by ReneSlowenski** [Ryochan7/antimicro#270]
Hi!

My user name is "René", which is supported by Windows and works fine with the vast majority of applications. When using antimicro though, a new profile folder "C:\Users\Ren�" is created. AntiMicro still works fine, but it is annoying to have a separate profile folder just for this program.

Regards,
René S.

**Comment by Ryochan7** [comment]
I am hoping that the most recent changes fixes this problem.
