### ISSUE TITLE
Pressing and holding multiple buttons

### ISSUE THREAD

**Issue by hacdieu** [Ryochan7/antimicro#271]
Hi, I am playing a game where i am holding buttons while walking around and they seem to stop working after the initial input. I am using Antimicro with an Afterglow 360 controller (360 controller) for my example.
EX: Hold (X) and (A) while moving left and right.
When i do that command using Antimicro; it keeps the X going but the A stops after the first time unless i stand still.

**Comment by Ryochan7** [comment]
There should be nothing in antimicro that would make this happen. Does this happen when playing games using native gamepad support or when using the Game Controller status program available for your operating system?
