### ISSUE TITLE
Can't seem to launch program

### ISSUE THREAD

**Issue by TemporalDistoriton** [Ryochan7/antimicro#272]
Hi!

I've installed the latest version of Antimicro on Fedora 22 and when I try run the program it seems to never open anything (It doesn't even show up in the task manager)

If I run it via console I get the following error:

antimicro: symbol lookup error: antimicro: undefined symbol: _ZN9QMetaType22registerNormalizedTypeERK10QByteArrayPFvPvEPFS3_S3_PKvEi6QFlagsINS_8TypeFlagEEPK11QMetaObject

What am I missing here?
I'm pretty sure I meet all dependencies (at least according to Yum extender I do!)

Thanks in advance for any help!

**Comment by ssokolow** [comment]
I'm no expert, but I think that means that the version of Qt you have installed isn't sufficiently like the one AntiMicro was compiled against. (Unlike C, C++ doesn't have a defined ABI, so it could be something as simple as "Qt and AntiMicro were compiled with GCC versions too far apart")

**Comment by TemporalDistoriton** [comment]
So what would be the best way to resolve this?

Is there a reference anywhere to the version used in Antimicro?

**Comment by ssokolow** [comment]
I'm not sure what the *best* way would be, but the simplest would probably be to install the [development headers](https://github.com/Ryochan7/antimicro#build-dependencies) (I'm not sure how RPM-based distros do it, but deb-based distros split them out into a separate package named by taking the base package and adding `-dev`) and then [compile Antimicro from source](https://github.com/Ryochan7/antimicro#building-under-linux).

**Comment by Ryochan7** [comment]
I am going to assume that this is probably related to a glibc update on your system. There is likely an ABI compatibility problem and the easiest way to fix this problem would be to recompile antimicro. Based on the output, I am going to assume that something is going wrong when calling qRegisterMetaType at the beginning of main.

**Comment by TemporalDistoriton** [comment]
Thanks that worked!

Thank you all

**Comment by jsbackus** [comment]
Hi TemporalDistoriton, I maintain the antimicro package for Fedora. Sorry for being late to the party. Just to confirm: 
* You downloaded a binary version from GitHub and it did not work?
* Recompiling the sources from GitHub did work?
* What version, 2.21?

GCC 5 was introduced in Fedora 22, which is likely the problem you experienced. I hope to update the package to 2.21 when I get a moment.

Thanks!
