### ISSUE TITLE
Wireless issue

### ISSUE THREAD

**Issue by R3cK17** [Ryochan7/antimicro#274]
When the software is running and you are using a x360 wireless setup, turning off the controller causes the software to hang. You then have to shut it down via task man. you can then run the software like normal, turn on the controller and it is fine. but once you turn it off you are presented with this issue again.
love the software though :)

**Comment by Ryochan7** [comment]
Unfortunately, I have not owned a wireless 360 controller for some time; I still have the wireless adapter though. I can only test this problem with my wired controllers and the unplug routine works fine for all of my controllers. I wouldn't think that the routine would be any different for people using a wireless Xbox 360 controller and I know that it used to work in previous versions of antimicro.

**Comment by R3cK17** [comment]
Actually I would like to retract that, after I updated from 2.20 to 2.21 it has been perfect. The issue is no more! :) Thankyou!
