### ISSUE TITLE
Bug:  Can not use an axis to select a set while held

### ISSUE THREAD

**Issue by EmperorArthur** [Ryochan7/antimicro#279]
While it is possible to use the Set Selector menu to set an axis to "Select Set 2 While Held"
This does not actually do anything.

Many controllers map their crappy D-Pads to axis, and it would be nice to use those to cycle through the different sets when one of the D-Pad buttons is held.

**Comment by Ryochan7** [comment]
I will have to look into this. Testing the functionality shows that switching to the second set works fine but switching back to the original set does not work. The back reference doesn't look like it gets populated so the second virtual button is not set up for set switching.

**Comment by Ryochan7** [comment]
Thank you for bringing up this problem. There are profiles that make use of set switching using triggers so this bug would have broken those profiles. The fix ended up being fairly minor and it was due to not updating a virtual method call so the wrong version of a method was being called.
