### ISSUE TITLE
Win Insider and AntiMicro app start error

### ISSUE THREAD

**Issue by R3cK17** [Ryochan7/antimicro#280]
Just installed latest Win Insider build 14251.rs1_release.160124-1059 and have tried uninstalling AM and running CCleaner to clean up reg, reinstalled and still get this error when trying to open the program
"The application was unable to start correctly (0xc0000142)
Tried running as admin and compat modes all to still get the same error :( re-downloaded the x64.msi as well and master zip files.

Any ideas?

**Comment by R3cK17** [comment]
Would also like to point out that I am having DirectX swap chain errors in several of my games using SweetFX. It seems to be an issue directly affected with this Insider build. I have a mod menu in GTAV and that now has to be manually injected to the process instead or it loading automatically.

I am not sure how to work around this DLL issue, but it would be great if there was a way to prevent this build from doing it. :(

**Comment by R3cK17** [comment]
Proud to announce that M$ Insider build 14257 has corrected all these issues! Hopefully it stays fixed :) love AM!

**Comment by Ryochan7** [comment]
That is good news that the problem was fixed.
