### ISSUE TITLE
Use mouse as "joystick"?

### ISSUE THREAD

**Issue by jbuttery** [Ryochan7/antimicro#285]
This may be silly in a way I'm not anticipating, but hey...can't hurt to ask, right?  :)

Would it be possible to set up AntiMicro to do with mice what it does with gamepads?  I'm playing a point-and-click adventure game right now almost entirely with a mouse (a Logitech G600, although I don't suppose that matters), and there's one key that I have to press a lot that it'd be really nice to map to middle-click (which the game doesn't use), or perhaps a scroll event, etc.

**Comment by Ryochan7** [comment]
Are you using Windows or Linux? If you are on Windows, I think that using AutoHotkey would be a better solution for that use case and it would be more flexible. I am not sure how this would be performed on the Linux side but I am sure there is some software out there that would handle that kind of remapping.

Having this type of functionality in antimicro is something that I probably couldn't integrate cleanly.

**Comment by jbuttery** [comment]
Fair enough.  I game on both, actually (trying to be GNU/Linux exclusively, but I'm also an avid indie gamer and realist so... :P).  This is also a very specific use case that I'll probably only encounter for this one game, and in point of fact I wound up solving the problem by using the Logitech utility to remap one of this mouse's plethora of extra buttons.  Thanks for looking into it, anyway.  And also, thanks for AntiMicro in the first place, it's allowed me to play quite a few games so far that would have been much less fun had I been stuck with the mouse and keyboard.  :)  I used to use Pinnacle Game Profiler, which is certainly an excellent piece of software, but I've switched over to AntiMicro and haven't looked back!

**Comment by Ryochan7** [comment]
Thanks for the compliment. I still use the alternative programs available every once in a while for testing. Xpadder is still my favorite alternative on Windows and it does a pretty good job of allowing many PC games to be playable with an Xbox 360 controller. I have a Pinnacle Game Profiler license as well but it hasn't been that useful for me. PGP has the best mapping system of any GUI based application that I have used but there are some issues that hold it back from overtaking Xpadder.

**Comment by jbuttery** [comment]
I'm going to go ahead and close this 'cause I agree it's a rare use case; it doesn't sound like it would justify the amount of work necessary to implement.  Also, I have other solutions to solve the practical problem.
