### ISSUE TITLE
Segfault on Set Select with 8-way

### ISSUE THREAD

**Issue by fauxmight** [Ryochan7/antimicro#287]
If the DPad is set to Eight Way mode in one set, switching TO that set will segfault.

Example: Mapping for a Saitek X52 (pro or non-pro) in Linux:

- Set DPad 1 Mode to 8-way in Set 1
- Set Button 6 to set select 2 while held
- Now, switching to set 2 works (with either button 6 OR just clicking the Set 2 button)
BUT
- When switching back to set 1 (either by releasing button 6 OR just clicking Set 1 button), antimicro segfaults.

If Dpad 1 is NOT in 8-way mode, there is no segfault.
If Dpad 1 is set to 8-way mode in Set2 but not Set1, switching to Set2 will segfault.
If Dpad 1 is set to 8-way in both Set1 and Set2, switching from either set to either set will segfault.

Same issue with current git version (9a11e4d) and with release 2.21 (from AUR) in Arch Linux.

**Comment by Ryochan7** [comment]
This ended up being due to a bad pointer issue when the dpad had no active direction. Thank you for bringing up this issue.
