### ISSUE TITLE
Gamepads not detected at all (Win7 x64)

### ISSUE THREAD

**Issue by maxlefou** [Ryochan7/antimicro#294]
None of my gamepads (1 gamepad and a linker for 3 gamepads) are detected at all by antimicro (the 2.21 release). No buttons appear in the window. When I click quickset it doesn't detect anything.
No matter if it's the x86 or x64 version, no matter if it's as administrator or not. 
My gamepads works fine and are detected by windows. All of my games and programs works ok with them. Only antimicro doesn't.
I'm on Windows 7 x64. 
Am I the only one with this problem?

**Comment by WAZAAAAA0** [comment]
Yes, I have reported this too https://github.com/Ryochan7/antimicro/issues/293 and the current solution is to downgrade to 2.20.2

**Comment by maxlefou** [comment]
thanks for the reply. will do this. Hope this problem will be fixed soon though :s

**Comment by Ryochan7** [comment]
Unfortunately this looks like it is a problem with SDL 2.0.4 that can't be worked around in the antimicro code. Version 2.0.4 of the SDL library was used with the latest Windows build of antimicro primarily for Windows 10 users. The only workaround right now is to replace the SDL2.dll file bundled with antimicro with the SDL2.dll file (version 2.0.3) bundled with antimicro 2.20.2. DirectInput controllers work perfectly fine when using the previous version of SDL.
