### ISSUE TITLE
Antimicro on boot

### ISSUE THREAD

**Issue by elachere** [Ryochan7/antimicro#298]
Hi, 

I'm trying to have antimicro started on boot. I'm on Raspbian, so I made a shell script (called launcher in /usr/bin) that runs antimicro with my config file, and added a `@reboot launcher > /path/to/logfile` to the crontab file.
Unfortunately,  it doesn't work, my log says : `antimicro: cannot connect to X server on boot`.
I made some research about this error, and tried a few things (xhost +, setting DISPLAY to my ip ..), nothing made it work.
Is there a way antimicro starts on boot with my config ? Many thanks

**Comment by ssokolow** [comment]
`@reboot` runs before the X server has started. If Raspbian is still running LXDE, you have two choices for running something on login:

1. Put a `.desktop` file in `~/.config/autostart`
2. Add a line (valid shell command-line, prefixed with `@`, if I remember correctly) to `~/.config/lxsession/<YOUR_PROFILE>/autostart`

**Comment by elachere** [comment]
Doing this right now, all lines in `autostart` don't end in `&` so I guess it's not needed. So I just add this line : `@launcher`, reboot and come back tell if it works.

**Comment by elachere** [comment]
It worked ! Thank you man you saved my day ! :)

**Comment by ssokolow** [comment]
Not a problem. :)
